### PR TITLE
Pull Request | Milestone 1.10

### PR DESCRIPTION
**Pull request by BelieveInBunny**
- [x] Option for users to only register with an invite link.
- [x] Enable/Disable User registration or Invite Function

### CODE REVIEW

**Review by WarmBeer — CHANGES_REQUESTED** [review]
Hey @BelieveInBunny , thank you for the PR. This has been a much requested feature, so the community will definitely appreciate your work!

But before we can merge this, could you please consider the following changes:

1. Add `backend/DATABASE`, `backend/DATABASE-shm` and `backend/DATABASE-wal` to `.gitignore`.
2. I'm not sure what the purpose of `backend/gobang` is. Could you explain to me why we need it or else remove it.
3. Add `backend/src/config.toml` to `.gitignore`. The config file should be automatically generated when running the backend.
4. Delete `backend/test.sql` and `backend/todo`. I believe these files are no longer necessary.
5. Set `server.port` in `frontend/vite.config.js` back to 8080.

Thank you.

**Comment by BelieveInBunny** [comment]
> 1. Add `backend/DATABASE`, `backend/DATABASE-shm` and `backend/DATABASE-wal` to `.gitignore`.
> 2. I'm not sure what the purpose of `backend/gobang` is. Could you explain to me why we need it or else remove it.
> 3. Add `backend/src/config.toml` to `.gitignore`. The config file should be automatically generated when running the backend.
> 4. Delete `backend/test.sql` and `backend/todo`. I believe these files are no longer necessary.
> 5. Set `server.port` in `frontend/vite.config.js` back to 8080.

yes, working on it now

**Comment by BelieveInBunny** [comment]
Hello @WarmBeer 
> 2. I'm not sure what the purpose of backend/gobang is. Could you explain to me why we need it or else remove it.

Regarding this, gobang is database management tool to help edit database. If you think it might be a good idea to keep it. awesome.
If not, we can remove it

**Comment by da2ce7** [comment]
> If you think it might be a good idea to keep it. awesome.

https://github.com/torrust/torrust/blob/90807f92b461ccf50482ae1d4ff78e05efdea8ba/backend/gobang/gobang

It is not good practice to include binaries within the repository.  It is better if we remove gobang from this pull request and instead update the [Backend's ReadMe File](https://github.com/torrust/torrust/blob/main/backend/README.md) with a link to: https://github.com/TaKO8Ki/gobang

**Comment by BelieveInBunny** [comment]
> It is not good practice to include binaries within the repository. It is better if we remove gobang from this pull request and instead update the [Backend's ReadMe File](https://github.com/torrust/torrust/blob/main/backend/README.md) with a link to: https://github.com/TaKO8Ki/gobang

I agree on it, I will note this for future coding

**Comment by BelieveInBunny** [comment]
Updated

**Comment by BelieveInBunny** [comment]
I hope everything is good now to merge the request.

**Comment by BelieveInBunny** [comment]
Thank you, I will close this pull request and create 2 seperate then

**Pull request closed without merging**
